DATASET:
  TRAIN_SIZE : 0.8
  VAL_SIZE : 0.2
  ROOT_PATH: "../cycle_splits/labeled_data"
  ROOT_ABSOLUTE_PATH: "/Users/emillundin/Desktop/Ski_project/SkiersProject/classification/cycle_splits/labeled_data"
  FILE_PREFIX: "labeled_cycles_"
  AUG:
    SMOOTHING: 2
    NORMALIZATION: true
    NORM_TYPE: full_signal

DATA_PRESET:
  CHOOSEN_JOINTS: 
    - LShoulder_x
    - RShoulder_y
    - LElbow_x
    - RElbow_x
    - LWrist_y
    - RWrist_x
    - LHip_y
    - RHip_x
    - LKnee_x
    - RKnee_x
    - LAnkle_x
    - RAnkle_x
  LABELS :
    unknown: 0
    gear2 : 1
    gear3 : 2
    gear4 : 3

TRAIN:
  BATCH_SIZE: 16
  EPOCHS: 100
  OPTIMIZER: 'adam'
  LOSS: focal_loss
  LR: 0.00016738085788752132
  PATIENCE: 100
  K_FOLDS: 5
  SEEDS:
    - 42
    - 2
    - 3
    - 4
    - 5
  NETWORK: 
    NETWORKTYPE: lstm
    LSTM:
      HIDDEN_SIZE: 256
      NUM_LAYERS: 2
      DROPOUT: 0.2
    MLP:
      HIDDEN_1: 251
      HIDDEN_2: 219

LOGGING:
  ROOT_PATH: "runs"
  TENSORBOARD_PATH: "tensorboard_runs"
  MODEL_DIR: "saved_models"
  PLOT_PATH: "plots"

OPTIMIZATION: 
  SEARCH_CONFIG: search_space.yaml
  OUTPUT_ROOT: "/Users/emillundin/Desktop/Ski_project/SkiersProject/classification/training/ray_tune"
  CHECKPOINTS:
    ENABLE: true
