DATASET:
  TRAIN_SIZE : 0.8
  VAL_SIZE : 0.2
  ROOT_PATH: "./data/split_data"
  FILE_PREFIX: "labeled_cycles_"
  TRAIN_FILE_NAME: "train_full.json"
  AUG:
    SMOOTHING: 2
    NORMALIZATION: true
    NORM_TYPE: full_signal

DATA_PRESET:
  CHOOSEN_JOINTS: 
    - LShoulder_x
    - LShoulder_y
    - RShoulder_x
    - RShoulder_y
    - LElbow_x
    - LElbow_y
    - RElbow_x
    - RElbow_y
    - LWrist_x
    - LWrist_y
    - RWrist_x
    - RWrist_y
    - LHip_x
    - LHip_y
    - RHip_x
    - RHip_y
    - LKnee_x
    - LKnee_y
    - RKnee_x
    - RKnee_y
    - LAnkle_x
    - LAnkle_y
    - RAnkle_x
    - RAnkle_y
    - Head_x
    - Head_y
    - Neck_x
    - Neck_y
    - Hip_y_ref
    - Hip_x_ref
    - LBigToe_x
    - LBigToe_y
    - RBigToe_x
    - RBigToe_y
    - LSmallToe_x
    - LSmallToe_y
    - RSmallToe_x
    - RSmallToe_y
    - LHeel_x
    - LHeel_y
    - RHeel_x
    - RHeel_y
    
  LABELS :
    unknown: 0
    gear2 : 1
    gear3 : 2
    gear4 : 3

TRAIN:
  BATCH_SIZE: 32
  EPOCHS: 21
  OPTIMIZER: 'adam'
  LOSS: focal_loss
  LR: 0.0001
  PATIENCE: 100
  K_FOLDS: 5
  SEEDS:
    - 42
    - 2
    - 3
    - 4
    - 5
  NETWORK: 
    NETWORKTYPE: mlp
    LSTM:
      HIDDEN_SIZE: 256
      NUM_LAYERS: 2
      DROPOUT: 0.2
    MLP:
      HIDDEN_1: 256
      HIDDEN_2: 64

LOGGING:
  ROOT_PATH: "./classification/training/runs"
  TENSORBOARD_PATH: "tensorboard_runs"
  MODEL_DIR: "saved_models"
  PLOT_PATH: "plots"
  BEST_EPOCH_PATH: "best_epoch_log"

OPTIMIZATION: 
  SEARCH_CONFIG: search_space.yaml
  OUTPUT_ROOT: "ray_tune"
  CHECKPOINTS:
    ENABLE: false
