  
VIDEO_PATH: e:\SkiProject\Expert_mistake_videos\DJI_0062.MP4
ALPHA_ARGS:
  SAVE_VIDEO: false
  VIS_FAST: true
  POSE_TRACK: true
  CFG_PATH: alphapose\configs\256x192_res50_lr1e-3_1x.yaml
  WEIGHTS_PATH: alphapose\pretrained_models\RegLoss100EpochNoFlipDPG.pth
  YOLO_WEIGHT_PATH: alphapose/detector/yolo/data/yolov3-spp.weights
  GPUS: "0"
  OUTPUT_PATH: ""
  SHOWBOX: False
  FORMAT: COCO
  SAVE_JSON: False
CLS_GEAR:
  NETTYPE: mlp
  MODEL_PATH: ./pretrained_models/trained_model_2025_04_11_15_03_lr0.0001_mlp_no_hip.pth
DTW:
  VIS_VID_PATH: e:\SkiProject\Expert_reference_videos
  SPLIT:
    LEFT: 
      CHOOSEN_JOINT: RAnkle
      CHOOSEN_EXTREMA: min
    RIGHT:
      CHOOSEN_JOINT: LAnkle
      CHOOSEN_EXTREMA: max
    FRONT:
      CHOOSEN_JOINT: RAnkle
      CHOOSEN_EXTREMA: min
  CHOOSEN_REF: Hip
  CHOOSEN_DIM: x
  GAUS_FILTER: True
  SIGMA_VALUE: 2 
  ORDER: 22
FEEDBACK:
  SAVE_VIDEO: False
  OUTPUT_PATH: ./data/feedback_videos
  MISTAKE_TYPE: general
  GENERAL_MODE:
    JOINT_ANGLES: 
      - ["RElbow", "RShoulder", "RHip"]
      - ["RHip", "Neck", "LHeel"]
      - ["LElbow", "LShoulder", "LHip"]
      - ["RAnkle", "RKnee", "RHip"]
    JOINTS_DISTANCES:
      - ["RKnee", "LKnee"]
      - ["RWrist", "LWrist"]
      - ["RWrist", "LWrist"]
    JOINTS_LINES_RELATIVE:
      - ["LHeel", "RElbow", "Neck", "LBigToe"]
    JOINTS_LINES_HORIZONTAL: 
      - ["LHeel", "RElbow"]
      - ["Neck", "LBigToe"]
  SAVE_STATISTICS: False
  OUTPUT_STATS: ./data/feedback_evaluation
