DATASET:
  TRAIN:
    TYPE: 'Halpe_26'
    ROOT: './data/halpe/'
    IMG_PREFIX: 'images/train2015'
    ANN: 'annotations/combined_train_annotations.json'
    AUG:
      FLIP: false
      ROT_FACTOR: 40
      SCALE_FACTOR: 0.3
      NUM_JOINTS_HALF_BODY: 11
      PROB_HALF_BODY: -1
  VAL:
    TYPE: 'Halpe_26'
    ROOT: './data/halpe/'
    IMG_PREFIX: 'images/val2017'
    ANN: 'annotations/combined_val_annotations.json'
  TEST:
    TYPE: 'Halpe_26_det'
    ROOT: './data/halpe/'
    IMG_PREFIX: 'images/val2017'
    DET_FILE: './exp/json/test_det_yolo.json'
    ANN: 'annotations/combined_val_annotations.json'
DATA_PRESET:
  TYPE: 'simple'
  SIGMA: 2
  NUM_JOINTS: 26
  IMAGE_SIZE:
  - 256
  - 192
  HEATMAP_SIZE:
  - 64
  - 48
MODEL:
  TYPE: 'FastPose'
  PRETRAINED: 'pretrained_models/model_expert_mixed_level.pth'
  TRY_LOAD: ''
  NUM_DECONV_FILTERS:
  - 256
  - 256
  - 256
  NUM_LAYERS: 50
LOSS:
  TYPE: 'MSELoss'
DETECTOR:
  NAME: 'yolo'
  CONFIG: 'alphapose/detector/yolo/cfg/yolov3-spp.cfg'
  WEIGHTS: 'alphapose/detector/yolo/data/yolov3-spp.weights'
  NMS_THRES: 0.6
  CONFIDENCE: 0.05
TRAIN:
  WORLD_SIZE: 4
  BATCH_SIZE: 32
  BEGIN_EPOCH: 0
  END_EPOCH: 2
  OPTIMIZER: 'adam'
  LR: 0.001
  LR_FACTOR: 0.1
  LR_STEP:
  - 20
  - 40
  DPG_MILESTONE: 60
  DPG_STEP:
  - 110
  - 130
